### ISSUE TITLE
Consider breaking queue/reporting out

### ISSUE THREAD

**Issue by nevir** [convoyinc/tracer#4]
Consider breaking the reporting logic out of `Tracer` (and `Queue`) and into a separate component (`Reporter`?) that users can swap out.  For example, our mobile app needs to be able to manage the queue so that it can persist it, and also treat it as a circular buffer so that it doesn't grow forever.

I think the `Queue`'s interface is pretty much what you'd want; it would just also own actually hitting servers, too (or calling `flushHandler` in the default case).

**Comment by vincecoppola** [comment]
Closing as this was added by #5
